[package]
name = "zerius"
version = "0.1.0"
cairo-version = "2.2.0"
authors = ["Polypox <shadowFux@proton.me>"]
description = "Zerius contracts for starknet."
readme = "README.md"
homepage = "https://zerius.io/"
repository = "https://github.com/zerius-io/zerius-starknet"
license = "BUSL-0.1"
keywords = ["erc-721", "onft", "zerius"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0-rc.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
